root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main main.go"
  bin = "tmp/main"
  include = ["*.go"]
  exclude = ["tmp","vendor"]

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  level = "debug"

